syntax = "proto3";

import "google/protobuf/empty.proto";
import "meta.proto";

option go_package = "./generated/protobuf";

message Config {
    string config = 1;
}

message DefaultConfigRequest {
    UserContext user = 1;
}

message ValidateAndSetConfigRequest {
    UserContext user = 1;
    Config config = 2;
}

message ValidateAndSetConfigResponse {
    oneof response {
        google.protobuf.Empty success = 1;
        Error error = 2;
    }
}

// A service that allows plugins to be configured through the Gotify server.
service Configurer {
    rpc DefaultConfig(DefaultConfigRequest) returns (Config);
    rpc ValidateAndSetConfig(ValidateAndSetConfigRequest) returns (ValidateAndSetConfigResponse);
}