syntax = "proto3";

import "google/protobuf/empty.proto";
import "meta.proto";

option go_package = "./generated/protobuf";

message ServerVersionInfo {
    string version = 1;
    string commit = 2;
    string buildDate = 3;
}

message StorageSaveRequest {
    uint64 userid = 1;
    bytes data = 2;
}

message StorageLoadResponse {
    uint64 userid = 1;
    bytes data = 2;
}

service Infra {
    rpc WhoAmI(google.protobuf.Empty) returns (Info);
    rpc GetServerVersion(google.protobuf.Empty) returns (ServerVersionInfo);
    rpc SaveConfig(StorageSaveRequest) returns (google.protobuf.Empty);
    rpc LoadConfig(google.protobuf.Empty) returns (StorageLoadResponse);
    rpc SendMessage(Message) returns (google.protobuf.Empty);
}