syntax = "proto3";
import "google/protobuf/any.proto";
import "google/protobuf/empty.proto";

option go_package = "./generated/protobuf";

message Error {
    google.protobuf.Any details = 1;
    string message = 2;
    string type = 3;
}

message UserContext {
    uint64 id = 1;
    string name = 2;
    bool admin = 3;
}

message Capabilities {
    optional uint32 Displayer = 1;
    optional uint32 Configurer = 2;
    optional uint32 Webhooker = 3;
}

message Info {
    string version = 1;
    string author = 2;
    string name = 3;
    string website = 4;
    string description = 5;
    string license = 6;
    string module_path = 7;
    Capabilities capabilities = 8;
}

message ExtrasValue {
    oneof value {
        string json = 1;
    }
}

message Message {
    string message = 1;
    string title = 2;
    int32 priority = 3;
    map<string, ExtrasValue> extras = 4;
}

message SetEnableRequest {
    UserContext user = 1;
    bool enable = 2;
}

enum Capability {
    DISPLAYER = 0;
    MESSENGER = 1;
    CONFIGURER = 2;
    STORAGER = 3;
    WEBHOOKER = 4;
}

message InstanceUpdate {
    oneof update {
        // enable support for a feature, must be one of the capabilities supported by the server
        Capability capable = 1;
        // send a message to the user
        Message message = 2;
        // update persistent storage
        bytes storage = 3;
    }
}

message UserInstanceRequest {
    // the server version info
    ServerVersionInfo serverVersion = 1;
    // the user context
    UserContext user = 2;
    // the webhook base path
    optional string webhookBasePath = 3;
    // the config
    optional bytes config = 4;
    // the storage
    optional bytes storage = 5;
}

message ServerVersionInfo {
    string version = 1;
    string commit = 2;
    string buildDate = 3;
    // supported capabilities of the gotify server itself
    repeated Capability capabilities = 4;
}

// The base plugin service, which includes a plugin metadata endpoint, a per-user master switch,
// and a user instance stream.
service Plugin {
    // get the plugin info
    rpc GetPluginInfo(google.protobuf.Empty) returns (Info);

    // set the enable state of a plugin instance
    rpc SetEnable(SetEnableRequest) returns (google.protobuf.Empty);
    
    // run a user instance
    rpc RunUserInstance(UserInstanceRequest) returns (stream InstanceUpdate);
}

